package client.logic;

public enum Interfaces {
    LOGIN_AND_REGIST_MENU,MAIN_MENU,ADMIN_MENU,EDIT_MENU,EDIT_NAME,EDIT_USERNAME,
    EDIT_PASSWORD,ENABLE_SHOW,DELETE_SHOW,CONSULT_SHOWS_FILTERS,CONSULT_SHOWS,SELECT_SHOW,
    CONSULT_SEATS,SELECT_SEATS,SUBMIT_RESERVATION,PAY_SEATS,ELIMINATE_RESERVATION,CONSULT_NOT_PAID_RESERVATION
}
